### ISSUE TITLE
执行命令报go函数未定义

### ISSUE THREAD

**Issue by Cuifc** [tioncico/curdAutomaticGeneration#2]
执行php easyswoole generation命令后报 Call to undefined function AutomaticGeneration\go()

函数位置：/vendor/tioncico/curd-automatic-generation/src/Generation.php的第27行。
请问这是什么引起。go函数，不是框架启用协程吗

**Comment by tioncico** [comment]
未开启swoole的短命名配置

**Comment by tioncico** [comment]
https://wiki.swoole.com/wiki/page/752.html

**Comment by Cuifc** [comment]
> https://wiki.swoole.com/wiki/page/752.html

Thanks
