### ISSUE TITLE
orm版本，生成model和controller之后，访问getall报错

### ISSUE THREAD

**Issue by xtstart-coder** [tioncico/curdAutomaticGeneration#3]
错误信息如下：
`Argument 2 passed to App\Model\AdminModel::getAll() must be of the type integer, null given, called in /easyswoole/App/HttpController/Admin/Admin.php on line 166<br />
#0 /easyswoole/App/HttpController/Admin/Admin.php(166): App\Model\AdminModel->getAll(1, NULL, 20)<br />
#1 /easyswoole/vendor/easyswoole/http/src/AbstractInterface/AnnotationController.php(168): App\HttpController\Admin\Admin->getAll()<br />
#2 [internal function]: EasySwoole\Http\AbstractInterface\AnnotationController->EasySwoole\Http\AbstractInterface\{closure}()<br />
#3 /easyswoole/vendor/easyswoole/http/src/AbstractInterface/Controller.php(113): call_user_func(Object(Closure))<br />
#4 /easyswoole/vendor/easyswoole/http/src/AbstractInterface/AnnotationController.php(171): EasySwoole\Http\AbstractInterface\Controller->__hook('getAll', Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response), Object(Closure))<br />
#5 /easyswoole/vendor/easyswoole/http/src/Dispatcher.php(182): EasySwoole\Http\AbstractInterface\AnnotationController->__hook('getAll', Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response))<br />
#6 /easyswoole/vendor/easyswoole/http/src/Dispatcher.php(137): EasySwoole\Http\Dispatcher->controllerHandler(Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response), '/admin/admin/ge...')<br />
#7 /easyswoole/vendor/easyswoole/easyswoole/src/Core.php(254): EasySwoole\Http\Dispatcher->dispatch(Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response))<br />
#8 {main}`

**Comment by LMFName** [comment]
![image](https://user-images.githubusercontent.com/11309372/71987570-72f78380-3269-11ea-8310-8b649518cb0b.png)
![image](https://user-images.githubusercontent.com/11309372/71987591-7be85500-3269-11ea-9b8f-177264baf8e0.png)

**Comment by xtstart-coder** [comment]
model
> 
public function getAll(int $page = 1, int $pageSize = 10, string $field = '*'): array
{
		$list = $this
		    ->withTotalCount()
			->order($this->schemaInfo()->getPkFiledName(), 'DESC')
		    ->field($field)
		    ->limit($pageSize * ($page - 1), $pageSize)
		    ->all();
		$total = $this->lastQueryResult()->getTotalCount();;
		return ['total' => $total, 'list' => $list];
	}

**Comment by xtstart-coder** [comment]
controller：
>     public function getAll()
    {
        $param = $this->request()->getRequestParam();
        $page = (int)($param['page'] ?? 1);
        $limit = (int)($param['limit'] ?? 20);

        $model = new AdminModel();
        $data = $model->getAll($page, $param['keyword'] ?? null, $limit);
        $this->writeJson(Status::CODE_OK, $data, 'success');
    }

**Comment by tioncico** [comment]
自动生成model的时候,有一个keyword配置$modelConfig->setKeyword  设置成非空就不会报错
这个后期会优化,这个工具的本质是生成一个通用的curd模板,然后根据自己的需求少量修改
